PRODUCT_COPY_FILES += \
vendor/amy/audio/Delete.ogg:$(TARGET_COPY_OUT_PRODUCT)/media/audio/ui/Delete.ogg \
vendor/amy/audio/Effect_Tick.ogg:$(TARGET_COPY_OUT_PRODUCT)/media/audio/ui/Effect_Tick.ogg \
vendor/amy/audio/HeiHei.mp3:$(TARGET_COPY_OUT_PRODUCT)/media/audio/ui/HeiHei.mp3 \
vendor/amy/audio/IncomingMessage.ogg:$(TARGET_COPY_OUT_PRODUCT)/media/audio/ui/IncomingMessage.ogg \
vendor/amy/audio/KeypressDelete.ogg:$(TARGET_COPY_OUT_PRODUCT)/media/audio/ui/KeypressDelete.ogg \
vendor/amy/audio/KeypressReturn.ogg:$(TARGET_COPY_OUT_PRODUCT)/media/audio/ui/KeypressReturn.ogg \
vendor/amy/audio/KeypressSpacebar.ogg:$(TARGET_COPY_OUT_PRODUCT)/media/audio/ui/KeypressSpacebar.ogg \
vendor/amy/audio/KeypressStandard.ogg:$(TARGET_COPY_OUT_PRODUCT)/media/audio/ui/KeypressStandard.ogg \
vendor/amy/audio/Lock.ogg:$(TARGET_COPY_OUT_PRODUCT)/media/audio/ui/Lock.ogg \
vendor/amy/audio/LowBattery.ogg:$(TARGET_COPY_OUT_PRODUCT)/media/audio/ui/LowBattery.ogg \
vendor/amy/audio/MessageSendOut.ogg:$(TARGET_COPY_OUT_PRODUCT)/media/audio/ui/MessageSendOut.ogg \
vendor/amy/audio/MessageSending.ogg:$(TARGET_COPY_OUT_PRODUCT)/media/audio/ui/MessageSending.ogg \
vendor/amy/audio/MessageSent.ogg:$(TARGET_COPY_OUT_PRODUCT)/media/audio/ui/MessageSent.ogg \
vendor/amy/audio/MusicShake.ogg:$(TARGET_COPY_OUT_PRODUCT)/media/audio/ui/MusicShake.ogg \
vendor/amy/audio/NumberPickerValueChange.ogg:$(TARGET_COPY_OUT_PRODUCT)/media/audio/ui/NumberPickerValueChange.ogg \
vendor/amy/audio/SystemDelete.ogg:$(TARGET_COPY_OUT_PRODUCT)/media/audio/ui/SystemDelete.ogg \
vendor/amy/audio/SystemError.ogg:$(TARGET_COPY_OUT_PRODUCT)/media/audio/ui/SystemError.ogg \
vendor/amy/audio/SystemTurnOff.ogg:$(TARGET_COPY_OUT_PRODUCT)/media/audio/ui/SystemTurnOff.ogg \
vendor/amy/audio/Unlock.ogg:$(TARGET_COPY_OUT_PRODUCT)/media/audio/ui/Unlock.ogg \
vendor/amy/audio/VideoRecord.ogg:$(TARGET_COPY_OUT_PRODUCT)/media/audio/ui/VideoRecord.ogg \
vendor/amy/audio/VideoStop.ogg:$(TARGET_COPY_OUT_PRODUCT)/media/audio/ui/VideoStop.ogg \
vendor/amy/audio/WirelessChargingStarted.ogg:$(TARGET_COPY_OUT_PRODUCT)/media/audio/ui/WirelessChargingStarted.ogg \
vendor/amy/audio/camera_click.ogg:$(TARGET_COPY_OUT_PRODUCT)/media/audio/ui/camera_click.ogg \
vendor/amy/audio/camera_focus.ogg:$(TARGET_COPY_OUT_PRODUCT)/media/audio/ui/camera_focus.ogg \
vendor/amy/audio/charge_wireless.ogg:$(TARGET_COPY_OUT_PRODUCT)/media/audio/ui/charge_wireless.ogg \
vendor/amy/audio/charging.ogg:$(TARGET_COPY_OUT_PRODUCT)/media/audio/ui/charging.ogg \
vendor/amy/audio/disconnect.ogg:$(TARGET_COPY_OUT_PRODUCT)/media/audio/ui/disconnect.ogg \
vendor/amy/audio/dynamic_alarm_speech.ogg:$(TARGET_COPY_OUT_PRODUCT)/media/audio/ui/dynamic_alarm_speech.ogg \
vendor/amy/audio/flashlight.ogg:$(TARGET_COPY_OUT_PRODUCT)/media/audio/ui/flashlight.ogg \
vendor/amy/audio/notice_audition.ogg:$(TARGET_COPY_OUT_PRODUCT)/media/audio/ui/notice_audition.ogg \
vendor/amy/audio/notification_beep_sound_1.ogg:$(TARGET_COPY_OUT_PRODUCT)/media/audio/ui/notification_beep_sound_1.ogg \
vendor/amy/audio/notification_beep_sound_10.ogg:$(TARGET_COPY_OUT_PRODUCT)/media/audio/ui/notification_beep_sound_10.ogg \
vendor/amy/audio/notification_beep_sound_2.ogg:$(TARGET_COPY_OUT_PRODUCT)/media/audio/ui/notification_beep_sound_2.ogg \
vendor/amy/audio/notification_beep_sound_3.ogg:$(TARGET_COPY_OUT_PRODUCT)/media/audio/ui/notification_beep_sound_3.ogg \
vendor/amy/audio/notification_beep_sound_4.ogg:$(TARGET_COPY_OUT_PRODUCT)/media/audio/ui/notification_beep_sound_4.ogg \
vendor/amy/audio/notification_beep_sound_5.ogg:$(TARGET_COPY_OUT_PRODUCT)/media/audio/ui/notification_beep_sound_5.ogg \
vendor/amy/audio/notification_beep_sound_6.ogg:$(TARGET_COPY_OUT_PRODUCT)/media/audio/ui/notification_beep_sound_6.ogg \
vendor/amy/audio/notification_beep_sound_7.ogg:$(TARGET_COPY_OUT_PRODUCT)/media/audio/ui/notification_beep_sound_7.ogg \
vendor/amy/audio/notification_beep_sound_8.ogg:$(TARGET_COPY_OUT_PRODUCT)/media/audio/ui/notification_beep_sound_8.ogg \
vendor/amy/audio/notification_beep_sound_9.ogg:$(TARGET_COPY_OUT_PRODUCT)/media/audio/ui/notification_beep_sound_9.ogg \
vendor/amy/audio/notification_beep_soundseq_1.ogg:$(TARGET_COPY_OUT_PRODUCT)/media/audio/ui/notification_beep_soundseq_1.ogg \
vendor/amy/audio/relieve.ogg:$(TARGET_COPY_OUT_PRODUCT)/media/audio/ui/relieve.ogg \
vendor/amy/audio/screenshot.ogg:$(TARGET_COPY_OUT_PRODUCT)/media/audio/ui/screenshot.ogg \
vendor/amy/audio/screenshot_kr.ogg:$(TARGET_COPY_OUT_PRODUCT)/media/audio/ui/screenshot_kr.ogg \
