PRODUCT_VERSION_MAJOR = 5
PRODUCT_VERSION_MINOR = 0

# Filter out random types, so it'll reset to UNOFFICIAL
ifeq ($(filter RELEASE NIGHTLY SNAPSHOT EXPERIMENTAL,$(AMY_BUILDTYPE)),)
    AMY_BUILDTYPE := UNOFFICIAL
endif

LINEAGE_VERSION_SUFFIX := $(LINEAGE_BUILD_DATE)-$(AMY_BUILDTYPE)-$(LINEAGE_BUILD)

LINEAGE_BUILDTYPE := AMY_BUILDTYPE

# Internal version
LINEAGE_VERSION := $(PRODUCT_VERSION_MAJOR).$(PRODUCT_VERSION_MINOR)-$(LINEAGE_VERSION_SUFFIX)

# Display version
LINEAGE_DISPLAY_VERSION := $(PRODUCT_VERSION_MAJOR)-$(LINEAGE_VERSION_SUFFIX)
AMY_VERSION := $(PRODUCT_VERSION_MAJOR)-$(PRODUCT_VERSION_MINOR)
