PRODUCT_VERSION_MAJOR = 15
PRODUCT_VERSION_MINOR = 0

AMYROM_BUILDTYPE ?= UNOFFICIAL

AMYROM_VERSION := $(PRODUCT_VERSION_MAJOR).$(PRODUCT_VERSION_MINOR)-$(AMYROM_BUILDTYPE)

# amyROM version properties
PRODUCT_SYSTEM_PROPERTIES += \
    ro.amyrom.version=$(AMYROM_VERSION) \
    ro.amyrom.releasetype=$(AMYROM_BUILDTYPE)
